<!-- ************ Modal adioS ************* -->

<div class="modal" id="adios" tabindex="-1" role="dialog">
	<div class="modal-dialog modal-dialog-centered" role="document" style="">
		<div class="modal-content <?php echo $baseclass; ?> " style="background-color: #FFF71F; border-radius: .8rem; box-shadow: .5rem .5rem .75rem rgba(0, 0, 0, .7);">
			<div class="modal-body " id='mensajeadios'><span class='spinner-border spinner-border-sm mr-3'  role='status'></span> <?php echo $st_despedida; ?></div>
		</div>
	</div>
</div>
<!-- ************ FIN Modal  adios ************* -->


<div class="abajo">
		<div class="logo fixed-bottom">
			<i class="fa fa-picture-o" aria-hidden="true"></i>
		</div>
		<ul>
			<li><a href="#">CEIP Berta Wilhelmi</a></li>
			<li><a href="about.html">About</a></li>
			<li><a href="#">Works</a></li>
			<li><a href="#">Contact</a></li>
		</ul>
			    
		<div class="secondary-links">
			<ul>
				<li><a href="#">CEIP Berta Wilhelmi</a></li>
				<li><a href="#">Privacy Policy</a></li>
			</ul>
			    
			<ul class="social">
				<li><a href="#">
					<i class="fa fa-github"></i>
				</a></li>
				<li><a href="#">
					<i class="fa fa-twitter"></i>
				</a></li>
				<li><a href="#">
					<i class="fa fa-codepen"></i>
				</a></li>
			</ul>
		</div>
	</div>

<!-- End your project here-->


  <!-- jQuery -->
  <script type="text/javascript" src="js/jquery.min.js"></script>
  <!-- Bootstrap tooltips -->
  <script type="text/javascript" src="js/popper.min.js"></script>
  <!-- Bootstrap core JavaScript -->
  <script type="text/javascript" src="js/bootstrap.min.js"></script>
  <!-- MDB core JavaScript -->
  <script type="text/javascript" src="js/mdb.min.js"></script>
  <!-- MDBootstrap Datatables  -->
<script type="text/javascript" src="js/datatables.min.js"></script>
<!-- Mis scpts -->
<script type="text/javascript" src="js/berta.js"></script>
  
  <!-- Your custom scripts (optional) -->


 